//The Main values that change a lot
var GameMute = true
var Office = undefined
var IsHost = false
var ShiftTime = 0
var Power = 1000
var PowerChange = 1000
var OfficeOn = true
var PowerUsage = 1
var MothCheck = null
var ActiveAnimatronics = []
var leftDoor = false
var rightDoor = false
var AllTimers = []
var ScreenCover = false
var textshown = true
var NightShift = 1
var Functions = [] //Lists all the office abilities
var FunctionControls = {}
var Deletables = [] //List for when the game ends so images cna be removed.
var Images = []
var Powered = true
var AudioAllow = true
var TimeSpotX = 0
var TimeSpotY = 0

addEventListener("selectstart", event => event.preventDefault());

//Changes what clicking the map camera buttons does
const OpenFunction = {
  Cameras: false,
  Doors: false,
  Heat: false,
  Light: false,
  Shock: false
}

//Admin Values
const DebugMode = true
var Godmode = false
var UnlimitedPower = false

//Allows quick check if animtronic is in a certain room
const RoomPlacement = {
  Cam1: [],
  Cam2: [],
  Cam3: [],
  Cam4: ['ElectricianAnamtronic', 'FreeRoamAnamtronic'],
  Cam5: [],
  Cam6: ['MothAnamtronic'],
  Cam7: [],
  Cam8: [],
  Cam9: [],
  Cam10: ['PowerDrainAnamtronic'],
  Cam11: [],
  Cam12: [],
  Cam13: [],
  Cam14: [],
  Cam15: [],
  Cam16: [],
  Cam17: [],
  Cam18: [],
  Cam19: [],
  Cam20: [],
  CamLeft: [],
  CamRight: [],
  CamOffice: [] //Don't ask
}

const OfficesRender = { //Contains the presets for the images
  ControlObject: {
    Ox: 0,
    Oy: 0,
    x: 0,
    y: 0,
    MaxLeft: 0,
    MaxRight: 3380,
    width: 500,
    height: 600,
    ScaleX: 500,
    ScaleY: 600,
    UIN: 'e',
    src: 'Assests/FrogHeadSet.png',
    Render: false,
    Class: 'ControlObject'
  },
  TitleScreen: {
    Ox: 0,
    Oy: 0,
    x: 0,
    y: 0,
    width: 1440,
    height: 789,
    ScaleX: Canvas_Width,
    ScaleY: Canvas_Height,
    UIN: 'Hi',
    src: 'Assests/TitleScreen.png',
    Render: true,
    Class: 'Fixed'
  },
  StaticTitle: {
    Ox: 0,
    Oy: 0,
    x: 0,
    y: 0,
    width: 1107,
    height: 671,
    FrameRate: 2,
    ScaleX: Canvas_Width,
    ScaleY: Canvas_Height,
    Frame: 0,
    Frames: 7,
    UIN: 'st',
    Opacity: 0.5,
    src: 'Assests/StaticScreenSprite.png',
    Render: true,
    FreezeFrame: false,
    Reverse: false,
    Class: 'AnimatedOpacityFixed'
  },
  CreateLobby: {
    Ox: 1105,
    Oy: 482,
    x: 0,
    y: 0,
    width: 74.5,
    height: 80,
    FrameRate: 1,
    ScaleX: 237,
    ScaleY: 237,
    Frame: 0,
    Frames: 3,
    UIN: 'BOTTON',
    src: 'Assests/BigRedButton_SpirteSheet.png',
    Render: true,
    FreezeFrame: true,
    Reverse: false,
    Class: 'AnimatedLeverEndAnimationAction',
    EndEffect: 'CreateLobby',
  },
  OfficeList: ['Office'],
  OfficeObjects: {
    Office: {
      Ox: 0,
      Oy: 0,
      x: 0,
      y: 0,
      xx: 0,
      yy: 0,
      MaxLeft: 0,
      MaxRight: 2450,
      width: Canvas_Width,
      height: Canvas_Height,
      ScaleX: Canvas_Width,
      ScaleY: Canvas_Height,
      UIN: 1,
      src: 'Assests/Office.png',
      Render: true,
      Class: 'BackgroundPanoramicReverseMove'
    },
    Desk1: {
      Ox: 350,
      Oy: 100,
      x: 0,
      y: 0,
      width: 1017,
      height: 921,
      ScaleX: 800,
      ScaleY: 700,
      UIN: 7,
      src: 'Assests/Office1Setup.png',
      Render: true,
      Class: 'Setup'
    },
    Desk2: {
      Ox: 350,
      Oy: 100,
      x: 0,
      y: 0,
      width: 1017,
      height: 921,
      ScaleX: 800,
      ScaleY: 700,
      UIN: 7,
      src: 'Assests/Office2Setup.png',
      Render: true,
      Class: 'Setup'
    },
    Desk3: {
      Ox: 350,
      Oy: 100,
      x: 0,
      y: 0,
      width: 1017,
      height: 921,
      ScaleX: 800,
      ScaleY: 700,
      UIN: 7,
      src: 'Assests/Office3Setup.png',
      Render: true,
      Class: 'Setup'
    },
    Desk4: {
      Ox: 350,
      Oy: 100,
      x: 0,
      y: 0,
      width: 1017,
      height: 921,
      ScaleX: 800,
      ScaleY: 700,
      UIN: 7,
      src: 'Assests/Office4Setup.png',
      Render: true,
      Class: 'Setup'
    }
  },
  OfficeOverlaysList: ['OfficeLight','LookLeft', 'LookRight', 'TriggerUp'],
  OfficeOverlaysObjects: {
    OfficeLight: {
      Ox: 146,
      Oy: 80,
      x: 0,
      y: 0,
      width: 1217.9,
      height: 716.7527,
      ScaleX: 1217.9,
      ScaleY: 716.7527,
      UIN: 1983,
      src: 'Assests/OfficeLight.png',
      Render: true,
      Class: 'Light'
    },
    LookLeft: {
      Ox: 0,
      Oy: 0,
      x: 0,
      y: 0,
      width: 40,
      height: 789,
      ScaleX: 40,
      ScaleY: 789,
      UIN: 1973,
      src: 'Assests/OfficeLeftLook.png',
      Render: true,
      Class: 'Fixed'
    },
    LookRight: {
      Ox: 1400,
      Oy: 0,
      x: 0,
      y: 0,
      width: 40,
      height: 789,
      ScaleX: 40,
      ScaleY: 789,
      UIN: 1963,
      src: 'Assests/OfficeRightLook.png',
      Render: true,
      Class: 'Fixed'
    },
    TriggerUp: {
      Ox: 220,
      Oy: 749,
      x: 0,
      y: 0,
      width: 1000,
      height: 40,
      ScaleX: 1000,
      ScaleY: 40,
      UIN: 1953,
      src: 'Assests/OfficeFlip.png',
      Render: true,
      Class: 'Fixed'
    },
  },
  CameraObjectList: ['CameraView', 'Animatronic_1', 'Animatronic_2', 'Animatronic_3', 'Static', 'Map'],
  CameraObjects: {
    Animatronic_1: {
      Ox: 0,
      Oy: 0,
      x: 0,
      y: 0,
      MaxLeft: 0,
      MaxRight: 3380,
      width: 0,
      height: 0,
      ScaleX: 0,
      ScaleY: 0,
      UIN: 30,
      src: 'Assests/FrogHeadSet.png',
      Render: false,
      Class: 'Fixed'
    },
    Animatronic_2: {
      Ox: 0,
      Oy: 0,
      x: 0,
      y: 0,
      MaxLeft: 0,
      MaxRight: 3380,
      width: 0,
      height: 0,
      ScaleX: 0,
      ScaleY: 0,
      UIN: 312,
      src: 'Assests/FrogHeadSet.png',
      Render: false,
      Class: 'Fixed'
    },
    Animatronic_3: {
      Ox: 0,
      Oy: 0,
      x: 0,
      y: 0,
      MaxLeft: 0,
      MaxRight: 3380,
      width: 0,
      height: 0,
      ScaleX: 0,
      ScaleY: 0,
      UIN: 300,
      src: 'Assests/FrogHeadSet.png',
      Render: false,
      Class: 'Fixed'
    },
    Static: {
      Ox: 0,
      Oy: 0,
      x: 0,
      y: 0,
      width: 1107,
      height: 671,
      FrameRate: 2,
      ScaleX: Canvas_Width,
      ScaleY: Canvas_Height,
      Frame: 0,
      Frames: 7,
      UIN: 2,
      Opacity: 0.5,
      src: 'Assests/StaticScreenSprite.png',
      Render: false,
      FreezeFrame: false,
      Reverse: false,
      Class: 'AnimatedOpacityFixed'
    },
    CameraView: {
      Ox: 0,
      Oy: 0,
      x: 0,
      y: 0,
      width: 1207,
      height: 681,
      ScaleX: Canvas_Width,
      ScaleY: Canvas_Height,
      UIN: 3,
      src: '',
      Render: false,
      Class: 'Fixed',
    },
    Map: {
      Ox: 1140,
      Oy: 430,
      x: 0,
      y: 0,
      Dx: 0,
      Dy: 0,
      width: 440,
      height: 435,
      ScaleX: 300,
      ScaleY: 300,
      UIN: 4,
      src: 'Assests/Map.png',
      Render: false,
      Class: 'DesignMoveFixed',
    },
    Shock9: {
      Ox: 1205,
      Oy: 472,
      x: 0,
      y: 0,
      width: 96,
      height: 40,
      ScaleX: 46,
      ScaleY: 19,
      UIN: 140,
      src: 'Assests/Shock9Button.png',
      Render: false,
      Class: 'Button'
    },
    Shock11: {
      Ox: 1276,
      Oy: 684,
      x: 0,
      y: 0,
      width: 96,
      height: 40,
      ScaleX: 46,
      ScaleY: 19,
      UIN: 148,
      src: 'Assests/Shock11Button.png',
      Render: false,
      Class: 'Button'
    },
    MapChangeButton: {
      Ox: 1350,
      Oy: 346,
      x: 0,
      y: 0,
      width: 100,
      height: 100,
      ScaleX: 50,
      ScaleY: 50,
      UIN: 159,
      src: '',
      Render: false,
      Class: 'Button'
    },
    Office1PowerDirect: {
      Ox: 1390,
      Oy: 455,
      x: 0,
      y: 0,
      width: 27,
      height: 14,
      ScaleX: 38,
      ScaleY: 17,
      UIN: 1559,
      src: 'Assests/NotPowered.png',
      Render: false,
      Class: 'Button'
    },
    Office2PowerDirect: {
      Ox: 1394,
      Oy: 699,
      x: 0,
      y: 0,
      width: 27,
      height: 14,
      ScaleX: 38,
      ScaleY: 17,
      UIN: 1359,
      src: 'Assests/NotPowered.png',
      Render: false,
      Class: 'Button'
    },
    Office3PowerDirect: {
      Ox: 1152,
      Oy: 699,
      x: 0,
      y: 0,
      width: 27,
      height: 14,
      ScaleX: 38,
      ScaleY: 17,
      UIN: 1259,
      src: 'Assests/NotPowered.png',
      Render: false,
      Class: 'Button'
    },
  },
  ScreenCover: {
    Ox: 0,
    Oy: 0,
    x: 0,
    y: 0,
    ScaleX: Canvas_Width,
    ScaleY: Canvas_Height,
    UIN: 'm',
    src: 'poland',
    Alpha: 0.2,
    Render: true,
    Class: 'Square',
    Colour: 'black'
  },
  Mask: {
    Ox: 0,
    Oy: 0,
    x: 0,
    y: 0,
    width: 1440,
    height: 789,
    ScaleX: Canvas_Width,
    ScaleY: Canvas_Height,
    UIN: 789,
    Frame: 0,
    Frames: 4,
    Reverse: true,
    FrameRate: 1,
    FreezeFrame: true,
    src: 'Assests/Mask_SpriteSheet.png',
    Render: true,
    Class: 'FixedAnimatedEndAnimationAction',
    EndEffect: 'Stop'
  },
  ConsoleList: ['OfficePowerConsole', 'ConsoleText'],
  ConsoleObjects: {
    OfficePowerConsole: {
      Ox: 387,
      Oy: 545,
      x: 0,
      y: 0,
      width: 74.5,
      height: 80,
      FrameRate: 1,
      ScaleX: 58.5,
      ScaleY: 64,
      Frame: 0,
      Frames: 3,
      UIN: 288,
      src: 'Assests/BigRedButton_SpirteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Class: 'AnimatedLeverEndAnimationAction',
      EndEffect: 'BigRedButtonPower',
    },
    ConsoleText: {
      Ox: 467,
      Oy: 550,
      x: 0,
      y: 0,
      width: 500,
      Colour: 'white',
      height: 10,
      FrameRate: 1,
      ScaleX: 58.5,
      ScaleY: 64,
      UIN: 228,
      src: 'Assests/BigRedButton_SpirteSheet.png',
      Render: true,
      Prompt: '',
      NextDialog: '',
      Multilined: true,
      Lines: 0,
      Font: '10px Arial',
      Text: 'Yap',
      Class: 'Text',
    }
  },
  PowerList: ['Office1Power','Office2Power','Office3Power','Office4Power'],
  PowerObjects: {
    Office1Power: {
      Ox: 725,
      Oy: 543,
      x: 0,
      y: 0,
      width: 48.5,
      height: 110,
      FrameRate: 2,
      ScaleX: 40,
      ScaleY: 90,
      Frame: 0,
      Frames: 4,
      UIN: 293,
      Name: 'Office1',
      src: 'Assests/Switch_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Class: 'AnimatedLeverEndAnimationAction',
      EndEffect: 'PowerSwitch',
    },
    Office2Power: {
      Ox: 824,
      Oy: 543,
      x: 0,
      y: 0,
      width: 48.5,
      height: 110,
      FrameRate: 2,
      ScaleX: 40,
      ScaleY: 90,
      Frame: 0,
      Frames: 4,
      UIN: 273,
      Name: 'Office2',
      src: 'Assests/Switch_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Class: 'AnimatedLeverEndAnimationAction',
      EndEffect: 'PowerSwitch',
    },
    Office3Power: {
      Ox: 725,
      Oy: 650,
      x: 0,
      y: 0,
      width: 48.5,
      height: 110,
      FrameRate: 2,
      ScaleX: 40,
      ScaleY: 90,
      Frame: 0,
      Frames: 4,
      UIN: 253,
      Name: 'Office3',
      src: 'Assests/Switch_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Class: 'AnimatedLeverEndAnimationAction',
      EndEffect: 'PowerSwitch',
    },
    Office4Power: {
      Ox: 824,
      Oy: 650,
      x: 0,
      y: 0,
      width: 48.5,
      height: 110,
      FrameRate: 2,
      ScaleX: 40,
      ScaleY: 90,
      Frame: 0,
      Frames: 4,
      UIN: 243,
      Name: 'Office4',
      src: 'Assests/Switch_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Class: 'AnimatedLeverEndAnimationAction',
      EndEffect: 'PowerSwitch',
    },
  },//BigRedButton_SpirteSheet.png
  DoorsList: [ 'LeftAnimatronic', 'RightAnimatronic', 'LeftDoor', 'RightDoor'],
  Doors: {
    LeftDoor: {
      Ox: 2559,
      Oy: 110,
      x: 0,
      y: 0,
      Dx: 0,
      Dy: 0,
      width: 282,
      height: 0,
      ScaleX: 212,
      ScaleY: 0,
      MaxScaleY: 645,
      UIN: 5,
      src: 'Assests/LeftDoor.png',
      Render: false,
      Animating: false,
      Class: 'DesignMoveDoor'
    },
    RightDoor: {
      Ox: 3605,
      Oy: 110,
      x: 0,
      y: 0,
      Dx: 0,
      Dy: 0,
      width: 282,
      height: 0,
      ScaleX: 212,
      ScaleY: 0,
      MaxScaleY: 650,
      UIN: 6,
      src: 'Assests/RightDoor.png',
      Render: false,
      Animating: false,
      Class: 'DesignMoveDoor'
    },
    LeftAnimatronic: {
      Ox: 2562,
      Oy: 0,
      x: 0,
      y: 0,
      width: 0,
      height: 0,
      ScaleX: 0,
      ScaleY: 0,
      UIN: 3045,
      src: 'Assests/FrogHeadSet.png',
      Render: false,
      Animating: false,
      Show: false,
      Class: 'Animatronic'
    },
    RightAnimatronic: {
      Ox: 0,
      Oy: 0,
      x: 0,
      y: 0,
      width: 0,
      height: 0,
      ScaleX: 0,
      ScaleY: 0,
      UIN: 3075,
      src: 'Assests/FrogHeadSet.png',
      Render: false,
      Animating: false,
      Show: false,
      Class: 'Animatronic'
    }
  },
  PowerBar: {
    Ox: 401,
    Oy: 144,
    x: 0,
    y: 0,
    Dx: 0,
    Dy: 0,
    width: 24,
    height: 171,
    ScaleX: 20,
    ScaleY: 130,
    UIN: 8,
    src: 'Assests/PowerBar-03.png',
    Render: true,
    Class: 'DesignMove'
  },
  DoorControllList: ['Office1Switch1', 'Office1Switch2', 'Office2Switch1', 'Office2Switch2', 'Office3Switch1', 'Office3Switch2', 'Office4Switch1', 'Office4Switch2'],
  DoorControllObjects: {
    Office1Switch1: {
      Ox: 401,
      Oy: 523,
      x: 0,
      y: 0,
      width: 48.5,
      height: 110,
      FrameRate: 2,
      ScaleX: 40,
      ScaleY: 90,
      Frame: 0,
      Frames: 4,
      UIN: 293,
      Name: 'Office1,Left',
      src: 'Assests/Switch_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Reverse: false,
      Class: 'AnimatedLeverEndAnimationAction',
      EndEffect: 'DoorLever',
    },
    Office1Switch2: {
      Ox: 446,
      Oy: 523,
      x: 0,
      y: 0,
      width: 48.5,
      height: 110,
      FrameRate: 2,
      ScaleX: 40,
      ScaleY: 90,
      Frame: 0,
      Frames: 4,
      UIN: 298,
      Name: 'Office1,Right',
      src: 'Assests/Switch_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Reverse: false,
      Class: 'AnimatedLeverEndAnimationAction',
      EndEffect: 'DoorLever',
    },
    Office3Switch1: {
      Ox: 401,
      Oy: 650,
      x: 0,
      y: 0,
      width: 48.5,
      height: 110,
      FrameRate: 2,
      ScaleX: 40,
      ScaleY: 90,
      Frame: 0,
      Frames: 4,
      UIN: 254,
      Name: 'Office3,Left',
      src: 'Assests/Switch_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Reverse: false,
      Class: 'AnimatedLeverEndAnimationAction',
      EndEffect: 'DoorLever',
    },
    Office3Switch2: {
      Ox: 446,
      Oy: 650,
      x: 0,
      y: 0,
      width: 48.5,
      height: 110,
      FrameRate: 2,
      ScaleX: 40,
      ScaleY: 90,
      Frame: 0,
      Frames: 4,
      UIN: 256,
      Name: 'Office3,Right',
      src: 'Assests/Switch_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Reverse: false,
      Class: 'AnimatedLeverEndAnimationAction',
      EndEffect: 'DoorLever',
    },
    Office2Switch1: {
      Ox: 602,
      Oy: 523,
      x: 0,
      y: 0,
      width: 48.5,
      height: 110,
      FrameRate: 2,
      ScaleX: 40,
      ScaleY: 90,
      Frame: 0,
      Frames: 4,
      UIN: 345,
      Name: 'Office2,Left',
      src: 'Assests/Switch_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Reverse: false,
      Class: 'AnimatedLeverEndAnimationAction',
      EndEffect: 'DoorLever',
    },
    Office2Switch2: {
      Ox: 647,
      Oy: 523,
      x: 0,
      y: 0,
      width: 48.5,
      height: 110,
      FrameRate: 2,
      ScaleX: 40,
      ScaleY: 90,
      Frame: 0,
      Frames: 4,
      UIN: 4589,
      Name: 'Office2,Right',
      src: 'Assests/Switch_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Reverse: false,
      Class: 'AnimatedLeverEndAnimationAction',
      EndEffect: 'DoorLever',
    },
    Office4Switch1: {
      Ox: 602,
      Oy: 650,
      x: 0,
      y: 0,
      width: 48.5,
      height: 110,
      FrameRate: 2,
      ScaleX: 40,
      ScaleY: 90,
      Frame: 0,
      Frames: 4,
      UIN: 231,
      Name: 'Office4,Left',
      src: 'Assests/Switch_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Reverse: false,
      Class: 'AnimatedLeverEndAnimationAction',
      EndEffect: 'DoorLever',
    },
    Office4Switch2: {
      Ox: 647,
      Oy: 650,
      x: 0,
      y: 0,
      width: 48.5,
      height: 110,
      FrameRate: 2,
      ScaleX: 40,
      ScaleY: 90,
      Frame: 0,
      Frames: 4,
      UIN: 342,
      Name: 'Office4,Right',
      src: 'Assests/Switch_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Reverse: false,
      Class: 'AnimatedLeverEndAnimationAction',
      EndEffect: 'DoorLever',
    },
  },
  JunctionList: ['PowerDial', 'Flick1', 'Flick2', 'Flick3', 'Flick4', 'Flick5', 'Flick6', 'Flick7', 'Flick8', 'Flick9', 'Flick10', 'Flick11', 'Flick12'],
  JunctionObjects: {
    PowerDial: {
      Ox: 460,
      Oy: 310,
      x: 0,
      y: 0,
      width: 59.7,
      height: 59.7,
      FrameRate: 2,
      ScaleX: 45,
      ScaleY: 45,
      Frame: 0,
      Frames: 5,
      UIN: 2283,
      src: 'Assests/Dial_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: true,
      Class: 'AnimatedEndAnimationAction',
      EndEffect: 'ConnectDial',
    },
    Flick1: {
      Ox: 431,
      Oy: 155,
      x: 0,
      y: 0,
      width: 19.3,
      height: 40,
      FrameRate: 2,
      ScaleX: 18,
      ScaleY: 33,
      Frame: 0,
      Frames: 3,
      UIN: 2883,
      src: 'Assests/Flick_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Class: 'AnimatedEndAnimationAction',
      Name: 1,
      EndEffect: 'FlickSwitch',
    },
    Flick2: {
      Ox: 450,
      Oy: 155,
      x: 0,
      y: 0,
      width: 19.3,
      height: 40,
      FrameRate: 2,
      ScaleX: 18,
      ScaleY: 33,
      Frame: 0,
      Frames: 3,
      UIN: 2884,
      src: 'Assests/Flick_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Class: 'AnimatedEndAnimationAction',
      Name: 2,
      EndEffect: 'FlickSwitch',
    },
    Flick3: {
      Ox: 468,
      Oy: 155,
      x: 0,
      y: 0,
      width: 19.3,
      height: 40,
      FrameRate: 2,
      ScaleX: 18,
      ScaleY: 33,
      Frame: 0,
      Frames: 3,
      UIN: 2885,
      src: 'Assests/Flick_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Class: 'AnimatedEndAnimationAction',
      Name: 3,
      EndEffect: 'FlickSwitch',
    },
    Flick4: {
      Ox: 488,
      Oy: 155,
      x: 0,
      y: 0,
      width: 19.3,
      height: 40,
      FrameRate: 2,
      ScaleX: 18,
      ScaleY: 33,
      Frame: 0,
      Frames: 3,
      UIN: 2886,
      src: 'Assests/Flick_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Class: 'AnimatedEndAnimationAction',
      Name: 4,
      EndEffect: 'FlickSwitch',
    },
    Flick5: {
      Ox: 431,
      Oy: 197,
      x: 0,
      y: 0,
      width: 19.3,
      height: 40,
      FrameRate: 2,
      ScaleX: 18,
      ScaleY: 33,
      Frame: 0,
      Frames: 3,
      UIN: 2887,
      src: 'Assests/Flick_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Class: 'AnimatedEndAnimationAction',
      Name: 5,
      EndEffect: 'FlickSwitch',
    },
    Flick6: {
      Ox: 449,
      Oy: 197,
      x: 0,
      y: 0,
      width: 19.3,
      height: 40,
      FrameRate: 2,
      ScaleX: 18,
      ScaleY: 33,
      Frame: 0,
      Frames: 3,
      UIN: 2888,
      src: 'Assests/Flick_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Class: 'AnimatedEndAnimationAction',
      Name: 6,
      EndEffect: 'FlickSwitch',
    },
    Flick7: {
      Ox: 468,
      Oy: 197,
      x: 0,
      y: 0,
      width: 19.3,
      height: 40,
      FrameRate: 2,
      ScaleX: 18,
      ScaleY: 33,
      Frame: 0,
      Frames: 3,
      UIN: 2889,
      src: 'Assests/Flick_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Class: 'AnimatedEndAnimationAction',
      Name: 7,
      EndEffect: 'FlickSwitch',
    },
    Flick8: {
      Ox: 487,
      Oy: 197,
      x: 0,
      y: 0,
      width: 19.3,
      height: 40,
      FrameRate: 2,
      ScaleX: 18,
      ScaleY: 33,
      Frame: 0,
      Frames: 3,
      UIN: 2890,
      src: 'Assests/Flick_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Class: 'AnimatedEndAnimationAction',
      Name: 8,
      EndEffect: 'FlickSwitch',
    },
    Flick9: {
      Ox: 431,
      Oy: 240,
      x: 0,
      y: 0,
      width: 19.3,
      height: 40,
      FrameRate: 2,
      ScaleX: 18,
      ScaleY: 33,
      Frame: 0,
      Frames: 3,
      UIN: 2891,
      src: 'Assests/Flick_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Class: 'AnimatedEndAnimationAction',
      Name: 9,
      EndEffect: 'FlickSwitch',
    },
    Flick10: {
      Ox: 450,
      Oy: 240,
      x: 0,
      y: 0,
      width: 19.3,
      height: 40,
      FrameRate: 2,
      ScaleX: 18,
      ScaleY: 33,
      Frame: 0,
      Frames: 3,
      UIN: 2892,
      src: 'Assests/Flick_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Class: 'AnimatedEndAnimationAction',
      Name: 10,
      EndEffect: 'FlickSwitch',
    },
    Flick11: {
      Ox: 468,
      Oy: 240,
      x: 0,
      y: 0,
      width: 19.3,
      height: 40,
      FrameRate: 2,
      ScaleX: 18,
      ScaleY: 33,
      Frame: 0,
      Frames: 3,
      UIN: 2893,
      src: 'Assests/Flick_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Class: 'AnimatedEndAnimationAction',
      Name: 11,
      EndEffect: 'FlickSwitch',
    },
    Flick12: {
      Ox: 488,
      Oy: 240,
      x: 0,
      y: 0,
      width: 19.3,
      height: 40,
      FrameRate: 2,
      ScaleX: 18,
      ScaleY: 33,
      Frame: 0,
      Frames: 3,
      UIN: 2894,
      src: 'Assests/Flick_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Class: 'AnimatedEndAnimationAction',
      Name: 12,
      EndEffect: 'FlickSwitch',
    },
  },
  FanList: ['Office1Switch3', 'Office1SwitchText', 'Office2Switch3', 'Office2SwitchText', 'Office3Switch3', 'Office3SwitchText', 'Office4Switch3', 'Office4SwitchText',],
  FanControll: {
    Office1Switch3: {
      Ox: 494,
      Oy: 523,
      x: 0,
      y: 0,
      width: 48.5,
      height: 110,
      FrameRate: 2,
      ScaleX: 40,
      ScaleY: 90,
      Frame: 0,
      Frames: 4,
      UIN: 288,
      Name: 'Office1',
      src: 'Assests/Switch_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Reverse: false,
      Class: 'AnimatedLeverEndAnimationAction',
      EndEffect: 'FanLever',
    },
    Office1SwitchText: {
      Ox: 545,
      Oy: 573,
      x: 0,
      y: 0,
      width: 48.5,
      height: 110,
      FrameRate: 3,
      ScaleX: 40,
      ScaleY: 90,
      Frame: 0,
      Frames: 4,
      UIN: 238,
      Text: 'none',
      Font: '20px Arial',
      Colour: 'green',
      Multilined: false,
      LineNumbers: 0,
      src: 'Assests/Switch_SpriteSheet.png',
      Render: true,
      Class: 'Text',
    },
    Office2Switch3: {
      Ox: 696,
      Oy: 523,
      x: 0,
      y: 0,
      width: 48.5,
      height: 110,
      FrameRate: 2,
      ScaleX: 40,
      ScaleY: 90,
      Frame: 0,
      Frames: 4,
      UIN: 290,
      Name: 'Office2',
      src: 'Assests/Switch_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Reverse: false,
      Class: 'AnimatedLeverEndAnimationAction',
      EndEffect: 'FanLever',
    },
    Office2SwitchText: {
      Ox: 745,
      Oy: 573,
      x: 0,
      y: 0,
      width: 48.5,
      height: 110,
      FrameRate: 3,
      ScaleX: 40,
      ScaleY: 90,
      Frame: 0,
      Frames: 4,
      UIN: 228,
      Text: 'none',
      Font: '20px Arial',
      Colour: 'green',
      Multilined: false,
      LineNumbers: 0,
      src: 'Assests/Switch_SpriteSheet.png',
      Render: true,
      Class: 'Text',
    },
    Office3Switch3: {
      Ox: 494,
      Oy: 650,
      x: 0,
      y: 0,
      width: 48.5,
      height: 110,
      FrameRate: 2,
      ScaleX: 40,
      ScaleY: 90,
      Frame: 0,
      Frames: 4,
      UIN: 289,
      Name: 'Office3',
      src: 'Assests/Switch_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Reverse: false,
      Class: 'AnimatedLeverEndAnimationAction',
      EndEffect: 'FanLever',
    },
    Office3SwitchText: {
      Ox: 545,
      Oy: 703,
      x: 0,
      y: 0,
      width: 48.5,
      height: 110,
      FrameRate: 3,
      ScaleX: 40,
      ScaleY: 90,
      Frame: 0,
      Frames: 4,
      UIN: 278,
      Text: 'none',
      Font: '20px Arial',
      Colour: 'green',
      Multilined: false,
      LineNumbers: 0,
      src: 'Assests/Switch_SpriteSheet.png',
      Render: true,
      Class: 'Text',
    },
    Office4Switch3: {
      Ox: 696,
      Oy: 650,
      x: 0,
      y: 0,
      width: 48.5,
      height: 110,
      FrameRate: 2,
      ScaleX: 40,
      ScaleY: 90,
      Frame: 0,
      Frames: 4,
      UIN: 291,
      Name: 'Office4',
      src: 'Assests/Switch_SpriteSheet.png',
      Render: true,
      FreezeFrame: true,
      Reverse: false,
      Reverse: false,
      Class: 'AnimatedLeverEndAnimationAction',
      EndEffect: 'FanLever',
    },
    Office4SwitchText: {
      Ox: 745,
      Oy: 703,
      x: 0,
      y: 0,
      width: 48.5,
      height: 110,
      FrameRate: 3,
      ScaleX: 40,
      ScaleY: 90,
      Frame: 0,
      Frames: 4,
      UIN: 218,
      Text: 'none',
      Font: '20px Arial',
      Colour: 'green',
      Multilined: false,
      LineNumbers: 0,
      src: 'Assests/Switch_SpriteSheet.png',
      Render: true,
      Class: 'Text',
    },
  },
  ShockList: ['Lever'],
  ShockControl: {
    Lever: {
      Ox: 995,
      Oy: 560,
      x: 0,
      y: 0,
      width: 109,
      height: 187,
      FrameRate: 2,
      ScaleX: 85,
      ScaleY: 147,
      Frame: 0,
      Frames: 15,
      UIN: 11,
      FreezeFrame: true,
      src: 'Assests/LeverDown.png',
      Render: true,
      Reverse: false,
      Class: 'AnimatedLeverEndAnimationAction',
      EndEffect: 'ShockLever',
    },
  },
  LightList: ['Lever', 'Light', 'Vent2', 'Vent3', 'Vent4'],
  LightControl: {
    Lever: {
      Ox: 658,
      Oy: 560,
      x: 0,
      y: 0,
      width: 109,
      height: 187,
      FrameRate: 2,
      ScaleX: 85,
      ScaleY: 147,
      Frame: 0,
      Frames: 15,
      UIN: 9,
      FreezeFrame: true,
      src: 'Assests/LeverDown.png',
      Render: true,
      Reverse: false,
      Class: 'AnimatedLeverEndAnimationAction',
      EndEffect: 'LightLever',
    },
    Light: {
      Ox: 764,
      Oy: 617,
      x: 0,
      y: 0,
      width: 49,
      height: 47,
      ScaleX: 42,
      ScaleY: 40,
      UIN: 10,
      src: 'Assests/LightOn-02.png',
      Render: true,
      Class: 'Light'
    },
    Vent1: {
      Ox: 574,
      Oy: 580,
      x: 0,
      y: 0,
      width: 51,
      height: 24,
      ScaleX: 46,
      ScaleY: 19,
      UIN: 112,
      src: 'Assests/Vent1Button-04.png',
      Render: true,
      Class: 'Button'
    },
    Vent2: {
      Ox: 546,
      Oy: 688,
      x: 0,
      y: 0,
      width: 51,
      height: 24,
      ScaleX: 46,
      ScaleY: 19,
      UIN: 124,
      src: 'Assests/Vent2Button-04.png',
      Render: true,
      Class: 'Button'
    },
    Vent3: {
      Ox: 458,
      Oy: 684,
      x: 0,
      y: 0,
      width: 51,
      height: 24,
      ScaleX: 46,
      ScaleY: 19,
      UIN: 135,
      src: 'Assests/Vent3Button-04.png',
      Render: true,
      Class: 'Button'
    },
    Vent4: {
      Ox: 428,
      Oy: 580,
      x: 0,
      y: 0,
      width: 49,
      height: 24,
      ScaleX: 46,
      ScaleY: 19,
      UIN: 146,
      src: 'Assests/Vent4Button-04.png',
      Render: true,
      Class: 'Button'
    },
  },
  FlashLight: {
    Ox: 220,
    Oy: 749,
    x: 0,
    y: 0,
    width: 829,
    height: 828,
    ScaleX: 829,
    ScaleY: 828,
    UIN: 'AAA',
    src: 'Assests/FlashLight.png',
    Render: false,
    Class: 'FixedMousePos'
  }
}

//Lists offices for easier load time
const Offices = {
  Office1: {
    RenderObjects: ['Office', 'PowerBar', 'Console', 'Junction', 'FlashLight', 'OfficeOverlays', 'Mask'],
    Suit: true,
    HasCameras: false,
    HasDoors: false,
    LightControl: true,
    ShockControl: true,
    SystemReset: true,
    DoorControl: false,
    PowerControl: false,
    HeatControl: false,
    Cameras: [],
    AddObjects: ['BigRedButtonPowerCheck', 'DialBox', 'Flick1Box', 'Flick2Box', 'Flick3Box', 'Flick4Box', 'Flick5Box', 'Flick6Box', 'Flick7Box', 'Flick8Box', 'Flick9Box', 'Flick10Box', 'Flick11Box', 'Flick12Box'],
    Mx: 440,
    My: 435,
    num: 1
  },
  Office2: {
    RenderObjects: ['Office', 'PowerBar', 'LightControl', 'ShockControl', 'OfficeOverlays', "Cameras", 'Doors'],
    Suit: false,
    HasCameras: true,
    HasDoors: true,
    LightControl: true,
    ShockControl: true,
    SystemReset: true,
    DoorControl: false,
    PowerControl: false,
    HeatControl: false,
    Cameras: ['Cam15', 'Cam3', 'Cam5', 'Cam6', 'Cam11', 'Cam14'],
    AddObjects: ['Cam15', 'Cam3', 'Cam5', 'Cam6', 'Cam11', 'Cam14', 'LightLeverBox', 'ShockLeverBox', 'LightVent2Box' ,'LightVent3Box', 'LightVent4Box', 'MapChangeButton', 'Shock9', 'Shock11'],
    Mx: 440,
    My: 435,
    num: 2
  },
  Office3: {
    RenderObjects: ['Office', 'PowerBar', 'TemperatureControl', 'DoorControl','OfficeOverlays', "Cameras", 'Doors'],
    Suit: false,
    HasCameras: true,
    HasDoors: true,
    LightControl: false,
    ShockControl: false,
    SystemReset: false,
    DoorControl: true,
    PowerControl: false,
    HeatControl: true,
    Cameras: ['Cam13', 'Cam4', 'Cam10', 'Cam12'],
    AddObjects: ['Cam13', 'Cam4', 'Cam10', 'Cam12', 'Office1DoorLeftBox', 'Office1DoorRightBox', 'Office2DoorLeftBox', 'Office2DoorRightBox', 'Office3DoorLeftBox', 'Office3DoorRightBox', 'Office4DoorLeftBox', 'Office4DoorRightBox',
                'Office1FanBox', 'Office2FanBox', 'Office3FanBox', 'Office4FanBox'],
    Mx: 10,
    My: 430,
    num: 3
  },
  Office4: {
    RenderObjects: ['Office', 'PowerBar', 'PowerControll', 'Console', 'OfficeOverlays', "Cameras", 'Doors'],
    Suit: false,
    HasCameras: true,
    HasDoors: true,
    LightControl: false,
    ShockControl: false,
    SystemReset: false,
    DoorControl: false,
    PowerControl: true,
    HeatControl: false,
    Cameras: ['Cam1', 'Cam8', 'Cam2', 'Cam9', 'Cam7'],
    AddObjects: ['Cam1', 'Cam8', 'Cam2', 'Cam9', 'Cam7', 'BigRedButtonPowerCheck', 'Office1PowerBox', 'Office2PowerBox', 'Office3PowerBox', 'Office4PowerBox', 'MapChangeButton', 'Office1PowerDirectBox', 'Office2PowerDirectBox', 'Office3PowerDirectBox'],
    Mx: 0,
    My: 0,
    num: 4
  }
}

//This controls the animatronics paths and other values specilized for them
const PowerDrainAnamtronic = {
  OriginRoom: 4,
  AILevel: 0,
  Room: 4,
  DrainAmount: 1,
  Path: {
    4: 10,
    10: [11, 2],
    11: 18,
    2: [9, 17],
    9: 7,
    7: 21,
    21: 17,
    17: 20,
    18: 20
  },
  Name: 'PowerDrainAnamtronic'
}
const ElectricianAnamtronic = {
  OriginRoom: 10,
  AILevel: 0,
  Room: 10,
  Path: {
    10: 2,
    2: [8, 9]
  },
  EnergyLevels: 100,
  Name: 'ElectricianAnamtronic'
}
const FreeRoamAnamtronic = {
  OriginRoom: 10,
  AILevel: 0,
  Room: 10,
  Office: undefined,
  Path: {
    10: [12, 11, 2],
    12: ['Left', 1],
    2: [8, 9, 17],
    11: [3, 3, 3, 5],
    3: 15,
    5: [15, 15, 14],
    15: ['Right', 13],
    13: 'Right',
    8: 1,
    1: 'Office',
    9: 7,
    7: 'Office',
    17: [11, 21, 18],
    18: 19,
    19: ['Office', 14],
    14: 'Left',
    21: 'Office',
    'Left': 'Office',
    'Right': 'Office'
  },
  Name: 'FreeRoamAnamtronic'
}
const MothAnamtronic = {
  OriginRoom: 6,
  AILevel: 0,
  Target: 0,
  Room: 6,
  Path: {
    6: 11,
    11: [5, 10, 10],
    5: 15,
    15: 'Office',
    10: [undefined, 12, 2],
    12: 'Office',
    2: 9,
    9: 7,
    7: 'Office'
  },
  Name: 'MothAnamtronic'
}
const EyeScanAnamtronic = {
  Room: 'middle',
  Stage: 0,
  AILevel: 0,
  LightLimitor: 0,
  LightAmount: 0
}
const PhantomAnamtronic = {
  AILevel: 0,
  Room: 'none',
  Door: 'none'
}

var MouseInfo = {
  x: null,
  y: null,
}

var MouseCollisions = ['CreateLobby', 'FindLobby']
const MouseCollisionsValues = {
  CreateLobbyButton: {
    x: 1105,
    y: 492,
    width: 237,
    height: 237,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Effect: {
      lever: 'CreateLobby'
    }
  },
  CreateLobby: {
    x: 51,
    y: 540,
    width: 225,
    height: 33,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Effect: {
      Lobby: 'Create'
    }
  },
  FindLobby: {
    x: 51,
    y: 465,
    width: 255,
    height: 33,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Effect: {
      Lobby: 'Find'
    }
  },
  Flick1Box: {
    x: 431,
    y: 155,
    width: 18,
    height: 33,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Name: 'Flick1',
    Effect: {
      lever: 'Flick'
    }
  },
  Flick2Box: {
    x: 449,
    y: 155,
    width: 18,
    height: 33,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Name: 'Flick2',
    Effect: {
      lever: 'Flick'
    }
  },
  Flick3Box: {
    x: 468,
    y: 155,
    width: 18,
    height: 33,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Name: 'Flick3',
    Effect: {
      lever: 'Flick'
    }
  },
  Flick4Box: {
    x: 488,
    y: 155,
    width: 18,
    height: 33,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Name: 'Flick4',
    Effect: {
      lever: 'Flick'
    }
  },
  Flick5Box: {
    x: 431,
    y: 197,
    width: 18,
    height: 33,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Name: 'Flick5',
    Effect: {
      lever: 'Flick'
    }
  },
  Flick6Box: {
    x: 449,
    y: 197,
    width: 18,
    height: 33,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Name: 'Flick6',
    Effect: {
      lever: 'Flick'
    }
  },
  Flick7Box: {
    x: 468,
    y: 197,
    width: 18,
    height: 33,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Name: 'Flick7',
    Effect: {
      lever: 'Flick'
    }
  },
  Flick8Box: {
    x: 487,
    y: 197,
    width: 18,
    height: 33,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Name: 'Flick8',
    Effect: {
      lever: 'Flick'
    }
  },
  Flick9Box: {
    x: 431,
    y: 240,
    width: 18,
    height: 33,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Name: 'Flick9',
    Effect: {
      lever: 'Flick'
    }
  },
  Flick10Box: {
    x: 450,
    y: 240,
    width: 18,
    height: 33,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Name: 'Flick10',
    Effect: {
      lever: 'Flick'
    }
  },
  Flick11Box: {
    x: 468,
    y: 240,
    width: 18,
    height: 33,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Name: 'Flick11',
    Effect: {
      lever: 'Flick'
    }
  },
  Flick12Box: {
    x: 488,
    y: 240,
    width: 18,
    height: 33,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Name: 'Flick12',
    Effect: {
      lever: 'Flick'
    }
  },
  DialBox: {
    x: 460,
    y: 310,
    width: 45,
    height: 45,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Name: 'PowerDial',
    Effect: {
      lever: 'PowerDial'
    }
  },
  Office2PowerBox: {
    x: 824,
    y: 543,
    width: 40,
    height: 90,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Switch: 'Office2Power',
    Effect: {
      lever: 'PowerSwitch'
    }
  },
  Office3PowerBox: {
    x: 725,
    y: 650,
    width: 40,
    height: 90,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Switch: 'Office3Power',
    Effect: {
      lever: 'PowerSwitch'
    }
  },
  Office4PowerBox: {
    x: 824,
    y: 650,
    width: 40,
    height: 90,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Switch: 'Office4Power',
    Effect: {
      lever: 'PowerSwitch'
    }
  },
  Office1PowerBox: {
    x: 725,
    y: 543,
    width: 40,
    height: 90,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Switch: 'Office1Power',
    Effect: {
      lever: 'PowerSwitch'
    }
  },
  BigRedButtonPowerCheck: {
    x: 387,
    y: 545,
    width: 58.5,
    height: 64,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Effect: {
      lever: 'BigRedButtonPower'
    }
  },
  Office1DoorLeftBox: {
    x: 401,
    y: 523,
    width: 40,
    height: 90,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Switch: 'Office1Switch1',
    Effect: {
      lever: 'DoorActivate'
    }
  },
  Office1DoorRightBox: {
    x: 447,
    y: 523,
    width: 40,
    height: 90,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Switch: 'Office1Switch2',
    Effect: {
      lever: 'DoorActivate'
    }
  },
  Office2DoorLeftBox: {
    x: 602,
    y: 523,
    width: 40,
    height: 90,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Switch: 'Office2Switch1',
    Effect: {
      lever: 'DoorActivate'
    }
  },
  Office2DoorRightBox: {
    x: 647,
    y: 523,
    width: 40,
    height: 90,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Switch: 'Office2Switch2',
    Effect: {
      lever: 'DoorActivate'
    }
  },
  Office3DoorLeftBox: {
    x: 401,
    y: 650,
    width: 40,
    height: 90,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Switch: 'Office3Switch1',
    Effect: {
      lever: 'DoorActivate'
    }
  },
  Office3DoorRightBox: {
    x: 447,
    y: 650,
    width: 40,
    height: 90,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Switch: 'Office3Switch2',
    Effect: {
      lever: 'DoorActivate'
    }
  },
  Office4DoorLeftBox: {
    x: 602,
    y: 650,
    width: 40,
    height: 90,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Switch: 'Office4Switch1',
    Effect: {
      lever: 'DoorActivate'
    }
  },
  Office4DoorRightBox: {
    x: 647,
    y: 650,
    width: 40,
    height: 90,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Switch: 'Office4Switch2',
    Effect: {
      lever: 'DoorActivate'
    }
  },
  Office1FanBox: {
    x: 494,
    y: 523,
    width: 40,
    height: 90,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Switch: 'Office1Switch3',
    Effect: {
      lever: 'FanActivate'
    }
  },
  Office2FanBox: {
    x: 696,
    y: 523,
    width: 40,
    height: 90,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Switch: 'Office2Switch3',
    Effect: {
      lever: 'FanActivate'
    }
  },
  Office3FanBox: {
    x: 494,
    y: 650,
    width: 40,
    height: 90,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Switch: 'Office3Switch3',
    Effect: {
      lever: 'FanActivate'
    }
  },
  Office4FanBox: {
    x: 696,
    y: 650,
    width: 40,
    height: 90,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Switch: 'Office4Switch3',
    Effect: {
      lever: 'FanActivate'
    }
  },
  LightLeverBox: {
    x: 658,
    y: 560,
    width: 85,
    height: 147,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Effect: {
      lever: 'LightActivate'
    }
  },
  LightVent1Box: {
    x: OfficesRender.LightControl.Vent1.Ox,
    y: OfficesRender.LightControl.Vent1.Oy,
    width: OfficesRender.LightControl.Vent1.ScaleX,
    height: OfficesRender.LightControl.Vent1.ScaleY,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Effect: {
      SelectVent: 'Vent1'
    }
  },
  LightVent2Box: {
    x: OfficesRender.LightControl.Vent2.Ox,
    y: OfficesRender.LightControl.Vent2.Oy,
    width: OfficesRender.LightControl.Vent2.ScaleX,
    height: OfficesRender.LightControl.Vent2.ScaleY,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Effect: {
      SelectVent: 'Vent2'
    }
  },
  LightVent3Box: {
    x: OfficesRender.LightControl.Vent3.Ox,
    y: OfficesRender.LightControl.Vent3.Oy,
    width: OfficesRender.LightControl.Vent3.ScaleX,
    height: OfficesRender.LightControl.Vent3.ScaleY,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Effect: {
      SelectVent: 'Vent3'
    }
  },
  LightVent4Box: {
    x: OfficesRender.LightControl.Vent4.Ox,
    y: OfficesRender.LightControl.Vent4.Oy,
    width: OfficesRender.LightControl.Vent4.ScaleX,
    height: OfficesRender.LightControl.Vent4.ScaleY,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Effect: {
      SelectVent: 'Vent4'
    }
  },
  ShockLeverBox: {
    x: 995,
    y: 560,
    width: 85,
    height: 147,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Effect: {
      lever: 'ShockActivate'
    }
  },
  DoorLeft: {
    x: 2569,
    y: 110,
    width: 212,
    height: 645,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Effect: {
      LightDoor: 'Left'
    }
  },
  DoorRight: {
    x: 3605,
    y: 110,
    width: 212,
    height: 645,
    Hitbox: true,
    Triggered: false,
    Move: true,
    Effect: {
      LightDoor: 'Right'
    }
  },
  ScreenTrigger: {
    x: 220,
    y: 749,
    width: 1000,
    height: 40,
    Hitbox: true,
    Triggered: false,
    Move: false,
    Effect: {
      FlipOut: 'Camera'
    }
  },
  LookLeftTrigger: {
    x: 1400,
    y: 0,
    width: 40,
    height: 789,
    Hitbox: true,
    Triggered: false,
    Move: false,
    Effect: {
      OfficeMove: 'Left'
    }
  },
  LookRightTrigger: {
    x: 0,
    y: 0,
    width: 40,
    height: 789,
    Hitbox: true,
    Triggered: false,
    Move: false,
    Effect: {
      OfficeMove: 'Right'
    }
  },
  Cam3: {
    x: 1160,
    y: 520,
    width: 40,
    height: 18,
    Hitbox: false,
    Move: false,
    Effect: {
      CameraChange: 3
    }
  },
  Cam4: {
    x: 1404,
    y: 602,
    width: 40,
    height: 18,
    Hitbox: false,
    Move: false,
    Effect: {
      CameraChange: 4
    }
  },
  Cam10: {
    x: 1400,
    y: 430,
    width: 40,
    height: 18,
    Hitbox: false,
    Move: false,
    Effect: {
      CameraChange: 10
    }
  },
  Cam12: {
    x: 1148,
    y: 438,
    width: 40,
    height: 18,
    Hitbox: false,
    Move: false,
    Effect: {
      CameraChange: 12
    }
  },
  Cam13: {
    x: 1390,
    y: 702,
    width: 40,
    height: 18,
    Hitbox: false,
    Move: false,
    Effect: {
      CameraChange: 13
    }
  },
  Cam5: {
    x: 1266,
    y: 520,
    width: 40,
    height: 18,
    Hitbox: false,
    Move: false,
    Effect: {
      CameraChange: 5
    }
  },
  Cam6: {
    x: 1302,
    y: 582,
    width: 40,
    height: 18,
    Hitbox: false,
    Move: false,
    Effect: {
      CameraChange: 6
    }
  },
  Cam11: {
    x: 1162,
    y: 435,
    width: 40,
    height: 18,
    Hitbox: false,
    Move: false,
    Effect: {
      CameraChange: 11
    }
  },
  Cam14: {
    x: 1383,
    y: 437,
    width: 40,
    height: 18,
    Hitbox: false,
    Move: false,
    Effect: {
      CameraChange: 14
    }
  },
  Cam15: {
    x: 1146,
    y: 696,
    width: 40,
    height: 18,
    Hitbox: false,
    Move: false,
    Effect: {
      CameraChange: 15
    }
  },
  Cam1: {
    x: 1155,
    y: 709,
    width: 40,
    height: 18,
    Hitbox: false,
    Move: false,
    Effect: {
      CameraChange: 14
    }
  },
  Cam2: {
    x: 1385,
    y: 693,
    width: 40,
    height: 18,
    Hitbox: false,
    Move: false,
    Effect: {
      CameraChange: 2
    }
  },
  Cam7: {
    x: 1392,
    y: 458,
    width: 40,
    height: 18,
    Hitbox: false,
    Move: false,
    Effect: {
      CameraChange: 15
    }
  },
  Cam9: {
    x: 1376,
    y: 514,
    width: 40,
    height: 18,
    Hitbox: false,
    Move: false,
    Effect: {
      CameraChange: 8
    }
  },
  Cam8: {
    x: 1218,
    y: 675,
    width: 40,
    height: 18,
    Hitbox: false,
    Move: false,
    Effect: {
      CameraChange: 9
    }
  },
  MapChangeButton: {
    x: 1350,
    y: 346,
    width: 50,
    height: 50,
    Hitbox: false,
    Move: false,
    Effect: {
      CameraMapChange: ''
    }
  },
  Shock9: {
    x: 1205,
    y: 472,
    width: 46,
    height: 19,
    Hitbox: false,
    Move: false,
    Effect: {
      SelectShock: 'Shock9'
    }
  },
  Shock11: {
    x: 1276,
    y: 684,
    width: 46,
    height: 19,
    Hitbox: false,
    Move: false,
    Effect: {
      SelectShock: 'Shock11'
    }
  },
  Office1PowerDirectBox: {
    x: 1390,
    y: 455,
    width: 38,
    height: 17,
    Hitbox: false,
    Move: false,
    Effect: {
      SelectPower: 'Office1'
    }
  },
  Office2PowerDirectBox: {
    x: 1394,
    y: 699,
    width: 38,
    height: 17,
    Hitbox: false,
    Move: false,
    Effect: {
      SelectPower: 'Office2'
    }
  },
  Office3PowerDirectBox: {
    x: 1152,
    y: 699,
    width: 38,
    height: 17,
    Hitbox: false,
    Move: false,
    Effect: {
      SelectPower: 'Office3'
    }
  },
}